import{i as n,S as c}from"./assets/vendor-5ObWk2rO.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();const u="45506482-0746cd613ccb32219c9653431";function m(e){if(!e.trim())return n.error({message:"Please enter a search query!",position:"topRight"}),Promise.resolve([]);const s=new URLSearchParams({key:u,q:e,image_type:"photo",orientation:"horizontal",safesearch:"true"});return document.querySelector(".loader").classList.remove("hidden"),fetch(`https://pixabay.com/api/?${s}`).then(r=>{if(!r.ok)throw new Error("Network response was not ok");return r.json()}).then(r=>(r.hits.length===0&&n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),r.hits)).catch(r=>{console.log(r),n.error({message:"An error occurred while fetching images. Please try again later.",position:"topRight"})}).finally(()=>{document.querySelector(".loader").classList.add("hidden")})}let l;const d=e=>` <li class="gallery-card">
      <a href="${e.largeImageURL}" class="gallery-item">
        <img class="gallery-img" src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
        <div class="info">
          <p class="info-item"><b>Likes:</b> ${e.likes}</p>
          <p class="info-item"><b>Views:</b> ${e.views}</p>
          <p class="info-item"><b>Comments:</b> ${e.comments}</p>
          <p class="info-item"><b>Downloads:</b> ${e.downloads}</p>
        </div>
      </a>
    </li>`;function p(e){const s=document.querySelector(".gallery"),r=e.map(a=>d(a)).join("");s.innerHTML=r,l=new c(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250}),l.refresh()}const h=document.querySelector(".submit-form"),f=document.querySelector(".search-input"),y=document.querySelector(".gallery");function g(){y.innerHTML=""}h.addEventListener("submit",e=>{e.preventDefault();const s=f.value.trim();if(!s){iziToast.error({message:"Please enter a search query!",position:"topRight"});return}g(),m(s).then(r=>{r.length>0&&p(r)}).catch(r=>{iziToast.error({message:"An error occurred. Please try again later.",position:"topRight"})})});
//# sourceMappingURL=index.js.map
